<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Core" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Redis" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <ProjectReference Include="../SwiftBets.Gateway.Application/SwiftBets.Gateway.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="RateLimiting/*.lua" />
  </ItemGroup>
</Project>
